name: Docker Image CI

on: 
  pull_request:
    types:
    - created 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file ./debian9_dev/Dockerfile --tag navitia/debian9_dev:$GITHUB_SHA
