name: Docker Image CI

on: 
  pull_request:
  push:
    branches:
    - master

jobs:
    info:
        runs-on: ubuntu-latest
        steps:
            - name: Dump GitHub context
              env:
                  GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"
            - name: Dump job context
              env:
                  JOB_CONTEXT: ${{ toJson(job) }}
              run: echo "$JOB_CONTEXT"
            - name: Dump steps context
              env:
                  STEPS_CONTEXT: ${{ toJson(steps) }}
              run: echo "$STEPS_CONTEXT"

    build:
      runs-on: ubuntu-latest

      strategy:
          matrix:
              docker_image_name: [debian9_dev, debian10_dev]

      steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file ./${{matrix.docker_image_name}}/Dockerfile --tag navitia/${{matrix.docker_image_name}}:$GITHUB_SHA
      - name: Publish image to Docker Hub
        if : github.event_name == 'push'
        run : | 
            docker login -u navitia -p ${{ secrets.docker_hub_pwd }}
            docker push navitia/${{matrix.docker_image_name}}
