name: Docker Image CI

on: 
  pull_request:
  push:
    branches:
    - master

jobs:
    build:
      runs-on: ubuntu-latest

      strategy:
          matrix:
              docker_image_name: [debian9_dev, debian10_dev]

      steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file ./${{matrix.docker_image_name}}/Dockerfile --tag navitia/${{matrix.docker_image_name}}
      - name: Publish image to Docker Hub
        if : github.event_name == 'push'
        run : | 
            docker login -u navitia -p ${{ secrets.docker_hub_pwd }}
            docker push navitia/${{matrix.docker_image_name}}:lastest
